config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users do
    resources :articles, only: [:new, :edit]
  end
  resources :articles, only: [:index, :show, :create, :update, :destroy]
  resources :user_import, only: [:index, :create]
  resources :cache, only: [:index, :show]

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  mount RedisBrowser::Web => '/redis'

  mount Logster::Web => "/logs"

end

app/models/article.rb
class Article < ActiveRecord::Base

  include Redis::Objects
  #value :redobj_attr, marshal: true, expiration: 1.hour
  hash_key :daily_views

  belongs_to :user, counter_cache: true, touch: true
  validates :title, :body, :user, presence: true

  after_create do 			user.redobj_articles_count.incr	 	end
	after_destroy do 			user.redobj_articles_count.decr	 	end
  #after_save do					self.redobj_attr = self.attributes 	end

  # query mongo collection for stats for this article by article_id
  def mongo_daily_views
  	ARTICLE_DAILY_VIEWS.find(:article_id => id).projection(:article_id => 0, :_id => 0).first
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  include Redis::Objects
  counter :redobj_articles_count

  validates :first_name, :last_name, :email, presence: true
  #validates :email, uniqueness: true

  has_many :articles

  after_update do
		UserGeocodeJob.perform_later(self) if zipcode.present? and zipcode_changed?
 	end

	def name
	  # adding method name to create unique cache_key
	  Rails.cache.fetch([cache_key, __method__]) do
			"#{first_name} #{last_name}"
	  end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all.includes(:user)
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to root_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to root_path, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :user_id)
    end
end

app/controllers/cache_controller.rb
class CacheController < ApplicationController

	def index
		render plain: index_cache
	end

	def show
		render plain: show_cache
	end

private

	def index_cache
	  Rails.cache.fetch([self.class.name, __method__], expires_in: 10.minutes) do
			"cached #{self.class.name}/#{__method__}"
	  end
	end

	def show_cache
	  Rails.cache.fetch([self.class.name, __method__, params[:id] ], expires_in: 10.minutes) do
			"cached #{self.class.name}/#{__method__}/#{params[:id]}"
	  end
	end

end

app/controllers/user_import_controller.rb
class UserImportController < ApplicationController

  def index
  end

  def create
  	# => simply using first user as the batch owner
    result = UserImportService.new(params[:file], User.first).perform()
    redirect_to :back, notice: result
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    render json: @users if params[:json] == 'true'
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # call service objects to fetch data from external APIs
    @github_data = JSON.parse GithubService.new(@user).perform
    @weather_data = JSON.parse WeatherService.new.perform(@user.zipcode)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :zipcode, :github_login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :user_id, as: :hidden, input_html: { value: params[:user_id] } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-info' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path, class: 'btn btn-info' %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path, class: 'btn btn-info' %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user.name %>
</p>

<%= link_to 'Back', user_path(@article.user), class: 'btn btn-info' %>

<hr>

<h4>These stats come from redis-objects daily_views hash_key</h4>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Date</th>
      <th>Views</th>
    </tr>
  </thead>

  <tbody>
    <% @article.daily_views.each do |dv| %>
      <tr>
        <td><%= dv.first %></td>
        <td><%= dv.second %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h4>These stats come from Mongo article_daily_views document.  The advantage of using Mongo vs Redis is you could query for specific dates across many articles</h4>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Date</th>
      <th>Views</th>
    </tr>
  </thead>

  <tbody>
    <% @article.mongo_daily_views.each do |dv| %>
      <tr>
        <td><%= dv.first %></td>
        <td><%= dv.second %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsRedis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
<hr>
<p id="notice"><%= notice %></p>
<%= yield %>
</div>

</body>
</html>

app/views/user_import/index.html.erb
<h1>User Import</h1>

<h4>Look at UserImportService.rb and UserImportJob.rb</h4>

<%= form_tag user_import_index_path, multipart: true do %>
  <%= file_field_tag :file, required: 'required' %>
  <br>
  <%= submit_tag 'Import', :class => 'btn btn-primary' %>
<% end %>

<br>

<%= link_to 'Back', users_path, class: 'btn btn-info' %>

app/views/user_import/new.html.erb
<h1>User Import</h1>

<h4>Look at UserImportService.rb and UserImportJob.rb</h4>

<%= form_tag user_import_index_path, multipart: true do %>
  <%= file_field_tag :file, required: 'required' %>
  <br>
  <%= submit_tag 'Import', :class => 'btn btn-primary' %>
<% end %>

<br>

<%= link_to 'Back', users_path, class: 'btn btn-info' %>

app/views/users/_articles.html.erb
<hr>

<h3>Articles</h3>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.user.name %></td>
        <td><%= link_to 'Show', article_path(article), class: 'btn btn-info btn-sm' %></td>
        <td><%= link_to 'Edit', edit_user_article_path(@user, article), class: 'btn btn-info btn-sm' %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_user_article_path(@user), class: 'btn btn-info' %>

app/views/users/_cache.html.erb
<hr>

<h3> Cached method calls </h3>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Name decorated:</strong>
  <%= @user.name_decorated %>
</p>

<hr>

<h3> Data cached from external APIs</h3>

<p>
  <strong>Github Avatar:</strong>
  <%= image_tag @github_data['avatar_url'], size: "100", alt: @user.name %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @weather_data['weather'].first['description'] if @weather_data['weather'] %>
  <%= 'need to get openweathermap.org API key' unless @weather_data['weather'] %>
</p>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :zipcode %>
    <%= f.input :github_login %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @user, class: 'btn btn-info' %> |
<%= link_to 'Back', users_path, class: 'btn btn-info' %>

app/views/users/index.html.erb
<% # Russian doll caching, creating a unique key %>
<% cache [controller_name, action_name, @users.map(&:id), @users.maximum(:updated_at) ] do %>

<h1>Listing Users</h1>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Zipcode</th>
      <th>Github Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <% # creates separate keys for each record, can be busted indivdiually %>
        <% cache [user] do %>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
          <td><%= user.zipcode %></td>
          <td><%= user.github_login %></td>
        <% end %>
        <td><%= link_to 'Show', user, class: 'btn btn-info btn-sm' %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-info btn-sm' %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: 'btn btn-info' %>

<hr>

<%= link_to 'Cached Controller', cache_index_path, class: 'btn btn-success btn-lg', target: '_blank' %>
<%= link_to 'Users JSON View', '/users.json', class: 'btn btn-success btn-lg', target: '_blank' %>
<%= link_to 'User Import', user_import_index_path, class: 'btn btn-success btn-lg' %>

<hr>

<%= link_to 'Sidekiq', sidekiq_web_path, class: 'btn btn-success btn-lg', target: '_blank' %>
<%= link_to 'Redis Browser', redis_browser_web_path, class: 'btn btn-success btn-lg', target: '_blank' %>
<%= link_to 'Logster', logster_web_path, class: 'btn btn-success btn-lg', target: '_blank' %>
<%= link_to 'New Relic', '/newrelic', class: 'btn btn-success btn-lg', target: '_blank' %>

<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class: 'btn btn-info' %>

app/views/users/show.html.erb
<%# This will cache portion of the view  %>
<% cache [@user] do %>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @user.zipcode %>
</p>

<p>
  <strong>Github Login:</strong>
  <%= @user.github_login %>
</p>

<p>
  <strong>Articles Count:</strong>
  <%= @user.articles_count %>
</p>

<p>
  <strong>Redis Objects Articles Count:</strong>
  <%= @user.redobj_articles_count %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @user.lat %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @user.lng %>
</p>

<% end %>

<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-info' %> |
<%= link_to 'Back', users_path, class: 'btn btn-info' %> |
<%= link_to 'JSON', user_path(@user) + '.json', class: 'btn btn-info' %>

<%= render 'cache' %>
<%= render 'articles' %>